hmcts/bastion-packer

ubuntu.pkr.hcl
=> DTSPO-4723 Add iage_name variable

ubuntu.pkr.hcl
=> DTSPO-4723 Add resource group name

ubuntu.pkr.hcl
=> DTSPO-4723 Update resource group

ubuntu.pkr.hcl
JIRA link
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No
=> DTSPO-4723 Update gallery name

azure-pipelines.yml
=> DTSPO-4723 Amend pipeline

provision-bastion.sh
=> install parallel utility

ubuntu.pkr.hcl
=> DTSPO-4723 - fix azure pipeline

azure-pipelines.yml
=> DTSPO-4723 - add spn to env"

azure-pipelines.yml
=> DTSPO-4723 - Using packer task

azure-pipelines.yml, ubuntu.pkr.hcl
- Using packer task
- Removing subscription variable
=> DTSPO-4723 - removing subscription variable

README.md
- Using packer task
- Removing subscription variable
- Adding client id and secret to hcl
- reverting condition on build task
- updating readme to reflect hcl and sig changes
=> DTSPO-4723 - Update readme

README.md
- Using packer task
- Removing subscription variable
- Adding client id and secret to hcl
- reverting condition on build task
- updating readme to reflect hcl and sig changes
- Updating minor typo:
=> DTSPO-4723 - updating typo in readme

provision-bastion.sh
=> DTSPO-6991  Install redis-cli

ubuntu.pkr.hcl
=> Use gen2 sku

ubuntu.pkr.hcl
Reverts hmcts/bastion-packer#30
=> Revert "Use gen2 sku"

provision-bastion.sh
=> DTSPO-12396 - install Openjdk 17 on non-prod bastion

ubuntu.pkr.hcl
DTSPO-12396
Request to install Openjdk 17 - new image to be created to apply to Bastion servers
```
[ ] Yes
[ X] No
```
=> DTSPO-12396 - Increase image version to allow Openjdk 17 install

provision-bastion.sh, ubuntu.pkr.hcl
DTSPO-12396
update postgresql install commands to apply later version
```
[ ] Yes
[ ] No
```
=> DTSPO-12396 - update postgresql install commands to apply later version

azure-pipelines.yml
https://tools.hmcts.net/jira/browse/DTSPO-14721
Update image gallery version automatically 
```
[ ] Yes
[x] No
```
=> automatically increment the image gallery version.

azure-pipelines.yml
=> downgraded packer version

provision-bastion.sh
=> installing azure-cli seperately

provision-bastion.sh
=> updated install command

provision-bastion.sh
Testing to install packages using apt command.
```
[ ] Yes
[ X] No
```
=> updated to instal curl and other packages

README.md, azure-pipelines.yml, provision-bastion.sh, renovate.json
- [ X] README and other documentation has been updated / added (if needed)
https://tools.hmcts.net/jira/browse/DTSPO-14720
https://tools.hmcts.net/jira/browse/DTSPO-14722
Added Scheduled run for the ADO pipeline, added github release and tags task and also added renovate to update minor versions.
```
[ ] Yes
[ X ] No
```
=> added schedule and renovate

azure-pipelines.yml, provision-bastion.sh, ubuntu.pkr.hcl
https://tools.hmcts.net/jira/browse/DTSPO-23931
- Upgrade bastion-packer image to Ubuntu 24.04
- Update pipeline to build image on PR, similar to jenkins-packer. Can be used to make sure provisioning script works without merging
=> Upgrade to Ubuntu 24.04

README.md
https://tools.hmcts.net/jira/browse/DTSPO-23931
- Updating readme to reference 24.04 instead of 18.04
=> Update readme to use 24.04
